-- Arbitri App reference data for baseline 2026-09-05.
-- Contains only system profiles, permissions, RBAC mappings, accounting
-- categories and a disabled WordPress source placeholder.

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

INSERT INTO `profiles` (`id`, `code`, `name`, `is_system`, `created_at`) VALUES (1,'admin','Amministratore',1,'2026-07-08 09:30:35');
INSERT INTO `profiles` (`id`, `code`, `name`, `is_system`, `created_at`) VALUES (2,'user','Utente',1,'2026-07-08 09:30:35');
INSERT INTO `profiles` (`id`, `code`, `name`, `is_system`, `created_at`) VALUES (3,'segreteria','Segreteria',1,'2026-07-12 21:51:42');

INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (1,'auth.me','Lettura identita utente autenticato','system',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (2,'dashboard.view','Visualizzazione dashboard','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (3,'movements.view','Visualizzazione movimenti','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (4,'movements.create','Creazione movimenti','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (5,'movements.edit','Modifica movimenti','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (6,'movements.delete','Eliminazione movimenti','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (7,'matches.view','Visualizzazione partite','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (8,'matches.create','Creazione partite','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (9,'matches.edit','Modifica partite','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (10,'matches.delete','Eliminazione partite','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (11,'seasons.view','Visualizzazione stagioni','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (12,'seasons.create','Creazione stagioni','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (13,'seasons.status.change','Cambio stato stagioni','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (14,'competitions.view','Visualizzazione competizioni','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (15,'competitions.create','Creazione competizioni','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (16,'competitions.edit','Modifica competizioni','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (17,'competitions.delete','Eliminazione competizioni','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (18,'teams.view','Visualizzazione squadre','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (19,'teams.create','Creazione squadre','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (20,'teams.edit','Modifica squadre','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (21,'teams.delete','Eliminazione squadre','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (22,'referees.view','Visualizzazione arbitri','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (23,'referees.create','Creazione arbitri','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (24,'referees.edit','Modifica arbitri','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (25,'referees.delete','Eliminazione arbitri','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (26,'fields.view','Visualizzazione stadi','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (27,'fields.create','Creazione stadi','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (28,'fields.edit','Modifica stadi','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (29,'fields.delete','Eliminazione stadi','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (30,'designations.view','Visualizzazione designazioni','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (31,'import.view','Visualizzazione import','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (32,'settings.view','Visualizzazione configurazione','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (33,'settings.manage','Gestione configurazione','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (34,'permissions.view','Visualizzazione permessi','page',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (35,'permissions.manage','Gestione permessi','action',1,'2026-07-08 09:30:35');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (37,'users.view','Visualizzazione utenti','page',1,'2026-07-08 09:58:28');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (38,'users.delete','Eliminazione utenti','action',1,'2026-07-11 20:29:20');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (39,'competitions.standings.manage','Gestione classifiche competizioni','action',1,'2026-07-11 21:54:10');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (40,'balance.view','Visualizzazione bilancio','page',1,'2026-07-12 21:51:42');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (41,'balance.export','Esportazione bilancio','action',1,'2026-07-12 21:51:42');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (42,'balance.approve','Approvazione bilancio','action',1,'2026-07-14 11:56:22');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (43,'balance.archive','Storicizzazione bilancio approvato','action',1,'2026-07-14 12:06:32');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (44,'designations.generate','Generazione proposta designazioni','action',1,'2026-07-14 23:48:24');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (45,'designations.edit','Modifica designazioni','action',1,'2026-07-14 23:48:24');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (46,'designations.confirm','Conferma designazioni','action',1,'2026-07-14 23:48:24');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (47,'designations.blacklist.manage','Gestione blacklist arbitro squadra','action',1,'2026-07-14 23:48:24');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (48,'users.create','Creazione utenti','action',1,'2026-07-17 13:49:02');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (49,'users.edit','Modifica utenti','action',1,'2026-07-17 13:49:02');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (50,'referee_availabilities.view','Visualizzazione disponibilita arbitri','action',1,'2026-07-18 21:53:29');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (51,'referee_availabilities.create','Creazione disponibilita arbitri','action',1,'2026-07-18 21:53:29');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (52,'referee_availabilities.edit','Modifica disponibilita arbitri','action',1,'2026-07-18 21:53:29');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (53,'referee_availabilities.delete','Eliminazione disponibilita arbitri','action',1,'2026-07-18 21:53:29');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (54,'import.manage','Configurazione sorgente import WordPress','action',1,'2026-08-25 22:47:20');
INSERT INTO `permissions` (`id`, `code`, `description`, `scope`, `active`, `created_at`) VALUES (55,'import.run','Esecuzione import WordPress','action',1,'2026-08-25 22:47:20');

INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,1,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,2,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,3,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,4,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,5,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,6,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,7,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,8,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,9,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,10,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,11,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,12,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,13,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,14,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,15,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,16,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,17,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,18,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,19,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,20,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,21,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,22,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,23,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,24,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,25,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,26,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,27,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,28,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,29,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,30,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,31,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,32,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,33,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,34,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,35,'2026-07-08 09:30:35');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,37,'2026-07-08 09:58:28');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,38,'2026-07-11 20:29:20');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,39,'2026-07-11 21:54:10');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,40,'2026-07-12 21:51:42');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,41,'2026-07-12 21:51:42');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,42,'2026-07-14 11:56:22');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,43,'2026-07-14 12:06:32');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,44,'2026-07-14 23:48:24');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,45,'2026-07-14 23:48:24');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,46,'2026-07-14 23:48:24');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,47,'2026-07-14 23:48:24');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,48,'2026-07-17 13:49:02');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,49,'2026-07-17 13:49:02');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,50,'2026-07-18 21:53:29');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,51,'2026-07-18 21:53:29');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,52,'2026-07-18 21:53:29');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,53,'2026-07-18 21:53:29');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,54,'2026-08-25 22:47:20');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (1,55,'2026-08-25 22:47:20');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,1,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,2,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,7,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,14,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,18,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,22,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,26,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (2,30,'2026-07-15 15:08:21');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (3,1,'2026-07-12 21:51:42');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (3,2,'2026-07-12 21:51:42');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (3,3,'2026-07-12 21:51:42');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (3,4,'2026-07-12 21:51:42');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (3,5,'2026-07-12 21:51:42');
INSERT INTO `profile_permissions` (`profile_id`, `permission_id`, `created_at`) VALUES (3,40,'2026-07-12 21:51:42');

INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (92,'Entrate',1,NULL,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (93,'Uscite',1,NULL,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (94,'Quote e iscrizioni',2,92,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (95,'Tesseramenti',2,92,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (96,'Sponsorizzazioni e pubblicita',2,92,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (97,'Eventi e tornei',2,92,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (98,'Iscrizioni competizioni',3,94,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (99,'Tessere atleti',3,95,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (100,'Sponsor',3,96,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (101,'Pubblicita',3,96,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (102,'Incassi evento',3,97,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (103,'Iscrizione campionato',4,98,1,1,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (104,'Iscrizione torneo',4,98,1,1,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (105,'Tessera annuale',4,99,0,1,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (106,'Sponsor associazione',4,100,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (107,'Materiale pubblicitario',4,101,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (108,'Torneo',4,102,1,1,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (109,'Festa / evento',4,102,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (110,'Altro evento',4,102,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (111,'Arbitri e ufficiali gara',2,93,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (112,'Costi competizioni',2,93,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (113,'Strutture e logistica',2,93,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (114,'Costi associazione',2,93,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (115,'Tesseramenti passivi',2,93,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (116,'Staff e collaboratori',2,93,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (117,'Compensi arbitri',3,111,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (118,'Osservatori',3,111,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (119,'Rimborsi arbitri',3,111,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (120,'Premi e coppe',3,112,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (121,'Materiale gara',3,112,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (122,'Stadi e campi',3,113,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (123,'Eventi',3,113,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (124,'Trasporti',3,113,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (125,'Affiliazioni',3,114,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (126,'Sede e segreteria',3,114,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (127,'Sito e software',3,114,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (128,'Tessere',3,115,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (129,'Rimborsi staff',3,116,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (130,'Arbitro centrale',4,117,1,0,1);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (131,'Assistente',4,117,1,0,1);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (132,'Terna',4,117,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (133,'Osservatore',4,118,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (134,'Rimborso spese',4,119,0,0,1);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (135,'Chilometraggio',4,119,0,0,1);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (136,'Coppe',4,120,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (137,'Premi',4,120,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (138,'Coppa disciplina',4,120,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (139,'Palloni',4,121,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (140,'Referti',4,121,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (141,'Attrezzatura sportiva',4,121,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (142,'Affitto campo',4,122,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (143,'Noleggio struttura',4,122,1,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (144,'Cena arbitri',4,123,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (145,'Premiazione',4,123,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (146,'Bar / ristoro',4,123,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (147,'Benzina',4,124,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (148,'Corrieri',4,124,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (149,'Noleggio mezzo',4,124,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (150,'ACSI',4,125,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (151,'Affiliazione federativa',4,125,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (152,'Cancelleria',4,126,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (153,'Segreteria',4,126,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (154,'Manutenzione',4,126,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (155,'Donazioni',4,126,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (156,'Altro sede',4,126,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (157,'Dominio',4,127,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (158,'Hosting / gestione sito',4,127,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (159,'Plugin / servizi digitali',4,127,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (160,'Canva / software',4,127,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (161,'Tessere ACSI / ente',4,128,0,1,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (162,'Staff',4,129,0,0,0);
INSERT INTO `categories` (`id`, `name`, `level`, `parent_id`, `allow_competition`, `allow_team`, `allow_referee`) VALUES (163,'Collaboratori',4,129,0,0,0);

INSERT INTO `external_sources`
  (`code`, `name`, `base_url`, `api_key_encrypted`, `enabled`)
VALUES
  ('wordpress_anwp', 'WordPress / AnWP Football Leagues', '', NULL, 0);

INSERT INTO `schema_migrations` (`version`, `description`)
VALUES ('baseline:2026-09-05', 'Schema and reference data baseline');
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
